apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  label:
    app: sistema-noticias
spec:
  containers:
    - name: sistema-noticias-container
      image: aluracursos/sistema-noticias:1
    Ports:
      - port:80
      
      
