apiVersion: v1
kind: service
metadata: 
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80
    #targetPort: 80
    nodePort: 30000 #32767
  selector:
    app: portal-noticias
  
